### ISSUE TITLE
Bug after disp line 44

### ISSUE THREAD

**Issue by wareck** [jonathanrjpereira/Bitcoin-Bar#7]
Hello
There is a small bug (not your script probably on the website)
When this step is executed  : 
    for i in range(len(disp)):
if "i" rise the line 44 script stop

Traceback (most recent call last):
  File "bcbar.py", line 48, in <module>
    show_message(device, disp[i], fill="white", font=proportional(LCD_FONT),scroll_delay = 0.02) #Change the value of 'scroll_delay' to change the Scrolling Speed
  File "/usr/local/lib/python3.7/dist-packages/luma/core/legacy/__init__.py", line 81, in show_message
    w, h = textsize(msg, font)
  File "/usr/local/lib/python3.7/dist-packages/luma/core/legacy/__init__.py", line 29, in textsize
    src = [c for ascii_code in txt for c in font[ord(ascii_code)]]
TypeError: 'NoneType' object is not iterable

**Comment by wareck** [comment]
the pull request added by ubik23 fix this issue ...
